FROM alpine:latest

LABEL Side="frontend"

RUN apk add --update nodejs npm curl

COPY . /front_side

WORKDIR /front_side

RUN npm install && npm cache clean --force

ENV NODE_OPTIONS=--max-old-space-size=8192

RUN npm run build

EXPOSE 3000

ENTRYPOINT ["npm", "start"]