version: "3.8"

services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend_api
    volumes:
      - frontend_code:/front_side
    ports:
      - "3000:3000"
    networks:
      - frontnet
  backend_api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend-api
    depends_on:
      - db
    networks:
      - frontnet
      - backnet
  db:
    image: postgres
    container_name: dA04_PG
    environment:
      - POSTGRES_USER=da04
      - POSTGRES_PASSWORD=da04PW
      - POSTGRES_DB=DA04_DB
    volumes:
      - da04_db:/var/lib/postgresql/data
    networks:
      - backnet
    restart: on-failure
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "root@ttcscn.net"
  #     PGADMIN_DEFAULT_PASSWORD: "root"
  #   depends_on:
  #     - db
  #   volumes:
  #     - pgadmin_cache:/var/lib/pgadmin
  #   ports:
  #     - "7000:80"
  #   networks:
  #     - backnet
  #   restart: on-failure

volumes:
  frontend_code:
  da04_db:
  # pgadmin_cache:

networks:
  frontnet:
  backnet:
