version: "3.8"

services:
  nginx:
    build:
      context: ./docker-nginx/
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - frontend
      - backend_api
    volumes:
      - ./docker-nginx/:/etc/nginx/
    ports:
      - "80:80"
    networks:
      - frontnet
      - backnet
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend_api
    volumes:
      - ./frontend/pages/:/front_side/pages/
      - ./frontend/styles/:/front_side/styles/
      # - frontend_code:/front_side
    networks:
      - frontnet
  backend_api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend-api
    depends_on:
      - db
    networks:
      - backnet
      - dbnet
  db:
    image: postgres:alpine
    container_name: dA04_PG
    environment:
      - POSTGRES_USER=da04
      - POSTGRES_PASSWORD=da04PW
      - POSTGRES_DB=DA04_DB
    volumes:
      - da04_db:/var/lib/postgresql/data
    networks:
      - dbnet
    restart: on-failure

volumes:
  # frontend_code:
  da04_db:

networks:
  frontnet:
  backnet:
  dbnet:
