version: "3.8"

services:
  nginx:
    build:
      context: ./docker-nginx/
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - frontend
      - backend_api
    volumes:
      - ./docker-nginx/:/etc/nginx/
      - backend_static:/srv/
    ports:
      - "80:80"
    networks:
      - frontnet
      - backnet
      - complier_net
    restart: on-failure
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend_api
    volumes:
      - ./frontend/:/front_side/
      - /front_side/node_modules
      - /front_side/.next
    networks:
      - frontnet
    restart: always
  backend_api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend-api
    depends_on:
      - db
    volumes:
      # - ./api_da4/:/code/api_da4/
      # - ./auth_da4/:/code/auth_da4/
      # - ./dA_04/:/code/dA_04/
      - backend_static:/code/static/
    networks:
      - backnet
      - dbnet
    command: ["./docker-django/migrate.sh"]
  db:
    image: postgres:alpine
    container_name: dA04_PG
    environment:
      - POSTGRES_USER=da04
      - POSTGRES_PASSWORD=da04PW
      - POSTGRES_DB=DA04_DB
    volumes:
      - da04_db:/var/lib/postgresql/data
    networks:
      - dbnet
    restart: on-failure
  php_complier:
    build:
      context: ./docker-compliers/php/
      dockerfile: Dockerfile
    container_name: php-complier
    networks:
      - complier_net
    volumes:
      - ./docker-compliers/php/:/app/

volumes:
  da04_db:
  backend_static:

networks:
  frontnet:
  backnet:
  dbnet:
  complier_net:
