GET http://localhost/api/course/

###

POST http://localhost/api/course/1/chapter/1/lesson/1/content/
Content-Type: application/json

{
    "lesson":1,
    "title":"test",
    "content":{
        "id":1,
        "value":"hahahhaha"
    }
}

###
GET http://localhost/auth/token/

###
PUT http://localhost/api/owner/course/course-3/make-publish/

###

GET http://localhost/ex/creator/exercise/get-users/

###

POST http://localhost/php/run/
Content-Type: application/json

{
    "code":"<?php echo 'My first PHP script!'; ?>"
}
